### ISSUE TITLE
Using the start scripts from the youtube video at 20:30 I cannot get nodemon to run.

### ISSUE THREAD

**Issue by SuperBerny** [codyseibert/tab-tracker#15]
I ran eslint --init and cannot get past this issue with nodemon.
Node v- 8.9.3
nodemon and eslint are both installed in the server folder's node_modules.
```
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "./node_modules/nodemon/bin/nodemon.js src/app.js --exec 'npm run lint && node'",
    "lint": "./nodemodules/.bin/eslint **/*.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "eslint": "^4.16.0",
    "nodemon": "^1.14.12"
  },
  "devDependencies": {
    "eslint-config-standard": "^11.0.0-beta.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1"
  }
}
```
I do node start and I get this error: 

> server@1.0.0 start C:\Users\brian\Desktop\Projects\tab-tracker\server
> ./node_modules/nodemon/bin/nodemon.js src/app.js --exec 'npm run lint && node'

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `./node_modules/nodemon/bin/nodemon.js src/app.js --exec 'npm run lint && node'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brian\AppData\Roaming\npm-cache\_logs\2018-02-03T00_31_54_299Z-debug.log

**Comment by seventh1976** [comment]
Edit the start script to this :
```json
"scripts": { 
    "start": "nodemon src/app.js --exec \"npm run lint && node\"",
    "lint": "eslint src/**/*.js"
}
```

**Comment by SuperBerny** [comment]
Ultimately that won't work either. All that does is tells you that ''npm' is not a recognized command.  I fixed it by coping the package.json file from the repo. I also removed eslint because I wanted to make comments at certain steps that I was new to and it crashes nodemon with each extra line or space after comments and I didn't feel like individually turning off rules.

**Comment by lmislm** [comment]
finally,maybe i solved it.all you just add `exit 0` behind "lint", like `"lint": "eslint src/**/*.js;exit 0"`.[details it's here](https://github.com/eslint/eslint/issues/2409)

**Comment by SuperBerny** [comment]
Appreciate it but I just uninstalled eslint. It's annoying. I appreciate what it does, but when it keeps crashing the server with nodemon when I want to add comments to parts that I want to study or it tells me that it expects a space after a comment and then when I add the space it tells me that I can't have trailing spaces after comments or that I need an extra line at the end of my code. All these things tell nodemon to stop running. I also use semicolons lol. So I said screw it. I'm here to learn, not rip my hair out.
