### ISSUE TITLE
npm install fails for server

### ISSUE THREAD

**Issue by cam424** [codyseibert/tab-tracker#32]
When running the client, I had no issues, but when running `npm install` within the server folder, I ran into this error. 

```npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.
npm ERR! Darwin 18.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v10.13.0
npm ERR! npm  v4.0.0
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cmohr/Documents/tab-tracker/server/npm-debug.log
Courtney-Mohr:server cmohr$ error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o (No such file or directory)
make: *** [Release/sqlite3.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/cmohr/Documents/tab-tracker/server/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/cmohr/Documents/tab-tracker/server/node_modules/sqlite3/lib/binding/node-v64-darwin-x64"
gyp ERR! cwd /Users/cmohr/Documents/tab-tracker/server/node_modules/sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok ```

**Comment by jpollone** [comment]
I'm running through each step of the tutorial and just installed sqlite3 today. I have version 4.0.6 installed, so maybe double-check your server/package.json and sqlite3 version or redo that package install?

`npm install --save sqlite3`

**Comment by cam424** [comment]
That did the trick. Could have sworn I reinstalled before but it's working now. Thanks!

**Comment by jpollone** [comment]
I was curious so I downloaded the zip and here's what I did to get `server` to compile and run. I haven't looked at `client` yet, but I assume it's similar and just a matter of updating packages.

`cd /server`
`sudo npm install -g npm-check-updates`
`ncu -a`
`sudo npm install`
`sudo npm install -g fsevents --unsafe-perm=true --allow-root`
`npm start`

Not sure about the issues with fsevents but I searched for errors similar and appended with a few parameters. By the way, there were a few linting issues so I just removed ` \"npm run lint && node\"` from package.json instead of correcting the files.

As a test, http://localhost:8081/songs returns the JSON songs.

**Comment by jebuscraisp** [comment]
what does ncu -a does ? , just curious..

**Comment by jpollone** [comment]
I'm sure I copied that after a Google search on updating NPM packages, but
probably a typo on my part and should have been a "-u". Or, maybe that
option checked for alpha packages too?

In any case, -a is not listed as an option, so I assume just "ncu" works
fine.

https://www.npmjs.com/package/npm-check-updates
