### ISSUE TITLE
Password compare is not allowing me to login

### ISSUE THREAD

**Issue by allanac** [codyseibert/tab-tracker#9]
Once adding bcrypt and the isPasswordValid function it will not allow a user to login. I have console log where it looks at the passwords but it keeps throwing me to the error of "Login information is incorrect". I have looked for hours, refactored the code, and cannot find the issue. Please help!

Console Log after grabbing user info from front-end.
```
`PAssword ------> 12345678

Stored password -----> $2a$08$nU4RxMzZPSWhjiLioYvPj.NoFIQMfPw6xPvH5Qn36hc0oNbwFpfaO

wtf Promise {
  _bitField: 134217728,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }

isPasswordValid------> false`
```
AuthenticationController.js
```
const isPasswordValid = await user.comparePassword(password)
   if (!isPasswordValid) {
        return res.status(403).send({
          error: 'The login information was incorrect'
        })
      }

```

**Comment by Johannes90** [comment]
@allanac I have the exact same issues as you have. I downgraded the sequelize and sqlite to the versions specified in this repo and then the login works for me. 

I got a deprecation warning when using the latest sequelize package that string-based symbols are not supported anymore. My suspicion is that it is related to this change.

**Comment by allanac** [comment]
@Johannes90 Thank you, that was the problem!
